// "use client";
import "./globals.css";
import { Akshar } from "next/font/google";
import Navigation from "../components/Navigation";
import Footer from "@/components/Footer";
import Providers from "../store/provider";
import { AuthProvider } from "../context/AuthContext";
import { CloudinaryProvider } from "@/context/cloudinaryContext";

const akshar = Akshar({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Ocean Allies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="bg-gradient-to-r from-slate-100 via-sky-50 to-slate-100 "
    >
      <Providers>
        <AuthProvider>
          <head>
            <link
              href="https://fonts.googleapis.com/css2?family=Akshar:wght@400;700&display=swap"
              rel="stylesheet"
            />
          </head>
          <body className={akshar.className}>
            <Navigation />
            <main>
              {/* Envuelve tu componente con CloudinaryContext */}
              <CloudinaryProvider cloudName="di8ocqpu1">
                {children}
              </CloudinaryProvider>
            </main>
            <Footer />
          </body>
        </AuthProvider>
      </Providers>
    </html>
  );
}
